quipp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'quipp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^quipper/', include('quipper.urls', namespace="quipper")),
    url(r'^admin/', include(admin.site.urls)),
)

quipper/urls.py
from django.conf.urls import patterns, url

from quipper import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

quipper/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __unicode__(self):
		return self.question
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <  now
		# return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

quipper/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from quipper.models import Choice, Poll

class IndexView(generic.ListView):
	template_name = 'quipper/index.html'
	context_object_name = 'latest_poll_list'

	def get_queryset(self):
		return Poll.objects.order_by('-pub_date')[:5]		
	# latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
	# context = {'latest_poll_list': latest_poll_list}
	# return render(request, 'quipper/index.html', context)

class DetailView(generic.DetailView):
	model = Poll
	template_name = 'quipper/detail.html'
	# poll = get_object_or_404(Poll, pk=poll_id)
	# return render(request, 'quipper/detail.html', {'poll': poll})

class ResultsView(generic.DetailView):
	model = Poll
	template_name = 'quipper/results.html'
    # poll = get_object_or_404(Poll, pk=poll_id)
    # return render(request, 'quipper/results.html', {'poll': poll})

def vote(request, poll_id):
	p = get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'quipper/detail.html', {
			'poll': p,
			'error_message': "You didn't select a choice."
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
    	return HttpResponseRedirect(reverse('quipper:results', args=(p.id,)))

quipper/templates/quipper/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quipper:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

quipper/templates/quipper/index.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quipper</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'quipper/style.css' %}" />
</head>
<body>
	{% if latest_poll_list %}
	    <ul>
	    {% for poll in latest_poll_list %}
	        <li><a href="{% url 'quipper:detail' poll.id %}">{{ poll.question }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}
</body>
</html>

quipper/templates/quipper/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'quipper:detail' poll.id %}">Vote again?</a>